[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-js-swc-core"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
swc_ecmascript = { version = "0.83.0", features = ["parser", "transforms", "module", "optimization", "react", "typescript", "utils", "visit", "codegen", "utils"] }
swc_ecma_preset_env = "0.62.0"
swc_common = { version = "0.14.2", features = ["tty-emitter", "sourcemap"] }
swc_atoms = "0.2.9"
indoc = "1.0.3"
serde = "1.0.123"
serde_bytes = "0.11.5"
Inflector = "0.11.4"
data-encoding = "2.3.2"
sha-1 = "0.9.4"
dunce = "1.0.1"
pathdiff = "0.2.0"
path-slash = "0.1.4"
